apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress
spec:
  hosts:
    - {{ .Values.keycloak.url }}
  gateways:
  - {{ .Values.keycloak.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-http
        port:
          number: 80