apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sources/keycloak
    repoURL: http://git-http-backend.git.svc/git/helm-charts.git
    targetRevision: master

    helm:
      releaseName: keycloak
      parameters:
        - name: keycloak.username
          value: admin
        - name: keycloak.password
          value: password
      values: |
        keycloak:
          ingress:
            enabled: true
            hosts:
              - keycloak.govk8s.dev
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              kubernetes.io/ingress.class: nginx
            tls:
              - hosts:
                - keycloak.govk8s.dev
                secretName: tls-govk8s-dev

  syncPolicy:
   automated:
     prune: true
     selfHeal: true