# Default values for keycloak-populator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: atoy3731/keycloak-populator
  tag: "1.0"
  pullPolicy: IfNotPresent

keycloak:
  url: http://keycloak.govk8s.dev
  admin_user: admin
  admin_password: password
  realm: master
  client_config_path: /configs/client.json